version: '3.8'
services:
  redis-stack-single:
    image: redis/redis-stack-server:7.2.0-v18
    ports:
      - "6382:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  redisinsight:
    image: redis/redisinsight:2.68
    ports:
      - "5542:5540"
# redis://docker.for.mac.localhost:6382
