version: '3.8'

services:
  redis-node-1:
    image: redis/redis-stack-server:latest
    container_name: redis-node-1
    command: redis-stack-server --cluster-enabled yes --cluster-config-file nodes.conf --port 6379
    volumes:
      - redis-node-1-data:/data
    network_mode: host
  redis-node-2:
    image: redis/redis-stack-server:latest
    container_name: redis-node-2
    command: redis-stack-server --cluster-enabled yes --cluster-config-file nodes.conf --port 6380
    volumes:
      - redis-node-2-data:/data
    network_mode: host
  redis-node-3:
    image: redis/redis-stack-server:latest
    container_name: redis-node-3
    command: redis-stack-server --cluster-enabled yes --cluster-config-file nodes.conf --port 6381
    volumes:
      - redis-node-3-data:/data
    network_mode: host
  redis-cluster-creator:
    image: redis/redis-stack-server:latest
    container_name: redis-cluster-creator
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    command: >
      bash -c "echo 'Waiting for Redis nodes to be ready...' && 
               sleep 10 && 
               echo 'Creating Redis cluster...' && 
               redis-cli --cluster create localhost:6379 localhost:6380 localhost:6381 --cluster-replicas 0 --cluster-yes || 
               (echo 'Cluster creation failed!' && exit 1)"
    network_mode: host
  redis-stack-single:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - "6382:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data: