spring.application.name: RediSearch

# Redis Configuration
spring:
  data:
    redis:
      host: localhost
      port: 6382
      database: 0

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

# Server Configuration
server:
  port: 8091
